ch100/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),  
    
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    
    path('search/', views.SearchFV.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

ch100/boards/urls.py
from django.urls import path, re_path
from boards import views

app_name = 'boards'

urlpatterns=[
    
    # Example:/boards/
    path('',views.BoardLV.as_view(), name='index'),

    # Example:/boards/post/
    path('boards/', views.BoardLV.as_view(), name='boards_list'),

    # Exampe:/boards/detail/django-example/
    re_path(r'^board/(?P<slug>[-\w]+)/$', views.BoardDV.as_view(), name='board_detail'),

    # Example:/boards/add/
    path('add/', views.BoardCreateView.as_view(), name='add'),

    # Example:/boards/change/
    path('change/', views.BoardChangeLV.as_view(), name='change'),
    
    # Example:/boards/99/update/    
    path('<int:pk>/update/', views.BoardUpdateView.as_view(), name='update'),
    
    # Example:/boards/add/99/delete/    
    path('<int:pk>/delete/', views.BoardDeleteView.as_view(), name='delete'),


]

ch100/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),

]

ch100/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import UserCreateView, UserCreateDoneTV
from django.conf.urls.static import static
from django.conf import settings

# from django.views.generic import ListView, DetailView
# from bookmark.models import Bookmark

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    path('boards/', include('boards.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),


    #class-based views
    # path('bookmark/', BookmarkLV.as_view(),name='index'),
    # path('bookmark/<int:pk>', BookmarkDV.as_view(),name='detail'),

    # #urls with view definition
    # path('bookmark/', ListView.as_view(model=Bookmark), name='index'),
    # path('bookmark/<int:pk>/', DetailView.as_view(model=Bookmark), name='detail'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ch100/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'

urlpatterns = [
    #Example: /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    #Example: /photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    #Example: /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    #Example: /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', views.AlbumCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', views.AlbumUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),

    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

]

ch100/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- 제목 블록 Start (기본값 My Blog Page) -->
    <title>    
        {% block title %}
            My Blog Page
        {% endblock %}
    </title>
    <!-- 제목 블록 End -->

    <!-- Bootstrap CSS only -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- font change [pretendard] -->
    <link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.5/dist/web/static/pretendard.css" />
    
    <!-- 공통 스타일 적용 Start -->
    <style>
        * {
            font-family: Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, "Helvetica Neue", "Segoe UI", "Apple SD Gothic Neo", "Noto Sans KR", "Malgun Gothic", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", sans-serif;
        }
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
        }
        #main-wrapper{
            margin: 60px 0;
            height: auto;
            min-height: 100%;
            padding-bottom: 266px;
        }
        footer {
            height: 266px;
            position: relative;
            transform : translateY(-100%);
            width: 100%;
            padding: 60px 0;
            background: #252629;
        }
        #contact_info  * {
            color: #96989c;
            font-size: 14px;
        }
    
        footer .footer_logo {
            padding-bottom: 24px;
            color: #fff;
            font-weight: 600;
        }
    </style>
    <!-- 공통 스타일 적용 End -->

    <!-- 스타일 블록 Start -->
    {% block extra-style %}
    {% endblock %}
    <!-- 스타일 블록 End -->
</head>

<body>
    <!-- 네비게이션 바 Start -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <li class="nav-item mx-0 btn">
            <a class="nav-link text-white mx-0 mb-0 font-weight-bold font-italic h3" href="{% url 'home' %}">권용재님</a>
        </li>
        <!-- <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">BLOG</span> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'bookmark:index' %}">BookMark</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'blog:index' %}">공지사항</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'boards:index' %}">자유게시판</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link text-white" href="{% url 'photo:index' %}">Photo</a>
                </li>
                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Edit Photo</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'photo:album_add' %}">add-Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">add-Photo</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_change' %}">change-Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_change' %}">change-Photo</a>
                    </div>
                </li>

                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                        <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                    </div>
                </li>
            </ul>
            
            <!-- <form class="form-inline my-2">
                <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form> -->
           
            
            <!--  -->
            <ul class="navbar-nav mx-5">
                <li class="nav-item dropdown mx-1 btn btn-dark">
                    {% if user.is_active %} <!-- 로그인된 상태라면 -->
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    </div>
                    {% else %} <!-- 로그인된 상태가 아니라면 -->
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        로그인 / 회원가입
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    </div>
                    {% endif %}
                </li>
            </ul>
            <!--  -->
        </div>
    </nav>
    <!-- 네비게이션 바 End -->

    <div id="main-wrapper">
        <div id="main-content" class="container">
            <!-- 콘텐츠 블록 Start -->
            {% block content %}
            {% endblock %}
            <!-- 콘텐츠 블록 End -->
        </div>
    </div>

    <!-- 푸터 Start -->
    <footer>
        <div class="container">
            <div class="footer_logo">My Blog</div>
            <div id="contact_info">
                <p>
                    <a class="text-decoration-none" href="tel:+821012345678"><i class="fa-solid fa-phone"></i>&emsp;010-1234-5678</a>
                    <br>
                    <a class="text-decoration-none" href="mailto:data.kwonyj@gmail.com"><i class="fa-solid fa-envelope"></i>&emsp;data.kwonyj@gmail.com</a>
                    <br>
                    <a class="text-decoration-none" href="https://www.instagram.com/dlwlrma" target="_blank"><i class="fa-brands fa-square-instagram"></i>&emsp;띠용</a>
                </p>
            </div>
            <p style="color:#646873">Copyright © <b>Kwon Yong Jae</b> All rights reserved.</p>
        </div>
    </footer>
    <!-- 푸터 End -->
</body>

<script src="https://kit.fontawesome.com/ec5623cc8e.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->
</html>

ch100/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra-style %}
<link href="{% static 'css/home.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="home-image">
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by Django and Bootstrap</h4>
</div>

<hr style="margin: 10px 0">


<div class="dummywrap title" style="text-align:center;">
    <h3 class="commu-title">
        <a class="tit-btn" style="cursor:context-menu;color:#000000;font-weight:bold;">
            &nbsp;&nbsp;&nbsp; 최신 글
        </a>
    </h3>
</div>

<div class="row text-center mt-5">
    <div class="col-sm-6">
        <article class="list-common_left">
            <style>
                #imid_83c7333fe51268f.tab-menu li{height:32;line-height:33px}
                #imid_83c7333fe51268f.tab-menu li:nth-of-type(1) a p{background-color:#f3f3f3;color:#000000;font-weight:normal}
                #imid_83c7333fe51268f.tab-menu li:nth-of-type(1) a p.on{background-color:#3d85c6;color:#ffffff;font-weight:bold}
                #imid_83c7333fe51268f.tab-menu li:nth-of-type(1) a p.hover{background-color:#3d85c6;color:#ffffff;font-weight:bold}
                #imid_83c7333fe51268f.tab-menu li:nth-of-type(2) a p{background-color:#f3f3f3;color:#000000;font-weight:normal}
                #imid_83c7333fe51268f.tab-menu li:nth-of-type(2) a p.on{background-color:#3d85c6;color:#ffffff;font-weight:normal}
                #imid_83c7333fe51268f.tab-menu li:nth-of-type(2) a p.hover{background-color:#3d85c6;color:#ffffff;font-weight:normal}
                #imid_83c7333fe51268f ~ *{display:none}
                #imid_83c7333fe51268f + div{display:block}
            </style>
            <script>        
                $(document).ready(function () { 
                    var tabbar = $('#imid_83c7333fe51268f.tab-menu');
                    var checked = 0;

                    $(document).on('mouseover', '#imid_83c7333fe51268f.tab-menu a', function(e) {
                        var me = $(this)
                        ,   ul = me.parent().parent()
                        ,   p = me.find('p')
                        ,   part = me.data('part')
                        ,   tablist = tabbar.siblings().filter('.tablist');
                        if (!p.hasClass('on')) {
                            ul.find('p').removeClass('on');
                            p.addClass('on');
                            tablist.hide();
                            tablist.filter('.tab'+part).show();

                        }
                        
                        e.preventDefault();
                    }); 

                    tabbar.siblings().each(function(i, v){
                        var self  = $(this);
                        var except = ['STYLE', 'SCRIPT'];
                        if(!self.hasClass('title') && ($.inArray(self[0].nodeName, except) == -1) && !self.hasClass('hidden')) {
                            if (checked > 0) {
                                self.addClass('tablist');
                                self.addClass('tab'+checked);
                            }else {
                                self.addClass('tablist').addClass('tab0');
                            }
                            checked++;
                        }
                    });



                });
            </script>
            <h3 class="hidden"></h3>
            <ul id="imid_83c7333fe51268f" class="tab-menu" data-length="2">
                <li><a href="http://127.0.0.1:8000/blog/" target="_self" data-part="0"><p class="on">공지사항</p></a></li>
            </ul>
            <div id="imid_ca38aee709a882d" class="list-bbs  tablist tab0">
                <style>
                    #imid_ca38aee709a882d{background-color:#ffffff}#imid_ca38aee709a882d div.tit{font-family:inherit;color:#000000}	
                </style>
                <!-- ==================== Module [list-bbs] Begin ==================== -->
                <h3 class="hidden"></h3>
                <ul class="basic board0 list-bbs">
                    {% for post in post_list %}
                    <li class="b2299">
                        <a href="{{ post.get_absolute_url }}">
                            <div class="txt-wrap">
                                <div class="cate" style="color:#3d85c6;float:left;margin-left:10px;">공지사항</div>
                                <div class="shorttitle" style="color:#222222;float:left;margin-left:10px;">{{ post }}</div>
                            </div>
                        </a>
                        <hr>
                    </li> 
                    {% endfor %}                                  
                </ul>
            </div>
        </article>
    </div>

    <div class="col-sm-6">
        <article class="list-common_right">
            <style>
                #imid_83c7333fe51268e.tab-menu li{height:32;line-height:33px}
                #imid_83c7333fe51268e.tab-menu li:nth-of-type(1) a p{background-color:#f3f3f3;color:#000000;font-weight:normal}
                #imid_83c7333fe51268e.tab-menu li:nth-of-type(1) a p.on{background-color:#3d85c6;color:#ffffff;font-weight:bold}
                #imid_83c7333fe51268e.tab-menu li:nth-of-type(1) a p.hover{background-color:#3d85c6;color:#ffffff;font-weight:bold}
                #imid_83c7333fe51268e.tab-menu li:nth-of-type(2) a p{background-color:#f3f3f3;color:#000000;font-weight:normal}
                #imid_83c7333fe51268e.tab-menu li:nth-of-type(2) a p.on{background-color:#3d85c6;color:#ffffff;font-weight:normal}
                #imid_83c7333fe51268e.tab-menu li:nth-of-type(2) a p.hover{background-color:#3d85c6;color:#ffffff;font-weight:normal}
                #imid_83c7333fe51268e ~ *{display:none}
                #imid_83c7333fe51268e + div{display:block}
            </style>
            <script>        
                $(document).ready(function () { 
                    var tabbar = $('#imid_83c7333fe51268f.tab-menu');
                    var checked = 0;

                    $(document).on('mouseover', '#imid_83c7333fe51268f.tab-menu a', function(e) {
                        var me = $(this)
                        ,   ul = me.parent().parent()
                        ,   p = me.find('p')
                        ,   part = me.data('part')
                        ,   tablist = tabbar.siblings().filter('.tablist');
                        if (!p.hasClass('on')) {
                            ul.find('p').removeClass('on');
                            p.addClass('on');
                            tablist.hide();
                            tablist.filter('.tab'+part).show();

                        }
                        
                        e.preventDefault();
                    }); 

                    tabbar.siblings().each(function(i, v){
                        var self  = $(this);
                        var except = ['STYLE', 'SCRIPT'];
                        if(!self.hasClass('title') && ($.inArray(self[0].nodeName, except) == -1) && !self.hasClass('hidden')) {
                            if (checked > 0) {
                                self.addClass('tablist');
                                self.addClass('tab'+checked);
                            }else {
                                self.addClass('tablist').addClass('tab0');
                            }
                            checked++;
                        }
                    });



                });
            </script>
            <h3 class="hidden"></h3>
            <ul id="imid_83c7333fe51268e" class="tab-menu" data-length="2">
                <li><a href="http://127.0.0.1:8000/boards/" target="_self" data-part="1"><p class="on">자유게시판</p></a></li>
            </ul>
            <div id="imid_ca38aee709a882g" class="list-bbs  tablist tab0">
                <style>
                    #imid_ca38aee709a882g{background-color:#ffffff}
                    #imid_ca38aee709a882g div.tit{font-family:inherit;color:#000000}	
                </style>
                <!-- ==================== Module [list-bbs] Begin ==================== -->
                <h3 class="hidden"></h3>
                <ul class="basic board0 list-bbs">
                    {% for board in board_list %}
                    <li class="b2299">
                        <a href="{{ board.get_absolute_url }}">        
                            <div class="text-wrap">
                                <div class="cate" style="color:#3d85c6;float:left;margin-left:10px;">게시판</div>
                                <div class="shorttitle" style="color:#222222;float:left;margin-left:10px;">{{ board }}</div>
                            </div>
                        </a>
                        <hr>
                    </li>                        
                    {% endfor %}           
                </ul>
            </div>
        </article>
    </div>
</div>




<div class="row text-center mt-5">
    <div class="col-sm-6">
        <a class="nav-link text-danger h3" href="{% url 'bookmark:index' %}">BookMark App</a>
        <!-- <h3>BookMark App</h3> -->
        <p>자주 가는 사이트 링크</p>
    </div>
    <div class="col-sm-6">
        <a class="nav-link text-warning h3" href="{% url 'blog:index' %}">공지사항</a>
        <!-- <h3>Blog App</h3> -->
        <p>공지하는곳</p>
    </div>
    <div class="col-sm-6">
        <a class="nav-link text-primary h3" href="{% url 'boards:index' %}">자유게시판</a>
        <!-- <h3>Blog App</h3> -->
        <p>자유로운 게시판</p>
    </div>
    <div class="col-sm-6">
        <a class="nav-link text-success h3" href="{% url 'photo:index' %}">Photo App</a>
        <p>짤 모음집</p>
    </div>
</div>


{% endblock %}

{% block extra-script %}
{% endblock %}

ch100/templates/template.html
<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->